name: Deploy Docker Image to Server via Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/test-docker-github:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/test-docker-github:latest

    - name: Deploy Docker image on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/test-docker-github:latest
          docker stop test-docker-github || true
          docker rm test-docker-github || true
          docker run -d --name test-docker-github ${{ secrets.DOCKERHUB_USERNAME }}/test-docker-github:latest

